config/routes.rb
Rails.application.routes.draw do
  resources :paintings

  resources :galleries

  devise_for :users
  resources :pages, :except => [:index, :new]

  get 'contacts/new', to: 'contacts#new'
  post 'contacts/create', to: 'contacts#create', as: :create_contact

  resources :homes, :except => [:index, :new]
  get ':id', to: 'homes#show' 
  root to: "homes#show", id: "home"

end

app/models/painting.rb
class Painting < ActiveRecord::Base
  belongs_to :gallery

  #accepts_nested_attributes_for :gallery
  mount_uploader :image, ImageUploader
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  before_action :set_painting, only: [:show, :edit, :update, :destroy]

  # GET /paintings
  # GET /paintings.json
  def index
    if params.has_key?(:type)
      if params[:type] == "surrealism" || params[:type] == "realism"
        @paintings = Painting.joins(:gallery).where("galleries.name = ?", params[:type].capitalize)
      else
        @paintings = Painting.all
      end
    else
      @paintings = Painting.all
    end
  end

  # GET /paintings/1
  # GET /paintings/1.json
  def show
  end

  # GET /paintings/new
  def new
    @painting = Painting.new
  end

  # GET /paintings/1/edit
  def edit
  end

  # POST /paintings
  # POST /paintings.json
  def create
    @painting = Painting.new(painting_params)

    respond_to do |format|
      if @painting.save
        format.html { redirect_to @painting, notice: 'Painting was successfully created.' }
        format.json { render :show, status: :created, location: @painting }
      else
        format.html { render :new }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paintings/1
  # PATCH/PUT /paintings/1.json
  def update
    respond_to do |format|
      if @painting.update(painting_params)
        format.html { redirect_to @painting, notice: 'Painting was successfully updated.' }
        format.json { render :show, status: :ok, location: @painting }
      else
        format.html { render :edit }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paintings/1
  # DELETE /paintings/1.json
  def destroy
    @painting.destroy
    respond_to do |format|
      format.html { redirect_to paintings_url, notice: 'Painting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_painting
      @painting = Painting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def painting_params
      params.require(:painting).permit(:name, :description, :image, :gallery_id)
    end
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/paintings/_form.html.haml
= form_for @painting, :html => {:multipart => true} do |f|
  - if @painting.errors.any?
    #error_explanation
      %h2= "#{pluralize(@painting.errors.count, "error")} prohibited this painting from being saved:"
      %ul
        - @painting.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name, :class => 'form-control'
  .form-group
    = f.label :description
    = f.text_area :description, :class => 'form-control'
  .form-group
    = f.label :image
    = f.file_field :image
  .form-group
    = f.label :gallery_id, "Gallery"
    = f.collection_select :gallery_id, Gallery.order(:name), :id, :name, include_blank: true
  %button.btn.btn-primary{:type => "submit"}
    Save

app/views/paintings/edit.html.haml
%h1 Editing painting

= render 'form'

= link_to 'Show', @painting
\|
= link_to 'Back', paintings_path

app/views/paintings/index.html.haml
.page-header
  %h1.text-centered
    Current Pieces
%p
  %ul.nav.nav-pills
    -unless params.has_key?(:type)
      %li.active
        =link_to "All", paintings_path
    -else
      %li
        =link_to "All", paintings_path

    -if params.has_key?(:type) && params[:type] == "realism"
      %li.active
        =link_to "Realism", paintings_path(:type => "realism")
    -else
      %li
        =link_to "Realism", paintings_path(:type => "realism")

    -if params.has_key?(:type) && params[:type] == "surrealism"
      %li.active
        =link_to "Surrealism", paintings_path(:type => "surrealism")
    -else
      %li
        =link_to "Surrealism", paintings_path(:type => "surrealism")

- @paintings.in_groups_of(2) do |works|
  .row
    - works.each do |painting|
      -if painting
        .col-md-6
          .thumbnail
            = link_to (image_tag painting.image_url(:product).to_s, :class => "img-responsive"), painting_path(painting.id)
            .caption.center-block.painting
              %h3=painting.name
              %p=simple_format painting.description
              %p
                =link_to "View details", painting_path(painting.id), :class => "btn btn-default"
  %hr


-#%h1 Listing paintings

-#%table
  -#%tr
    -#%th Name
    -#%th Description
    -#%th Image
    -#%th Gallery
    -#%th
    -#%th
    -#%th

  -#- @paintings.each do |painting|
    -#%tr
      -#%td= painting.name
      -#%td= painting.description
      -#%td= painting.image
      -#%td= painting.gallery
      -#%td= link_to 'Show', painting
      -#%td= link_to 'Edit', edit_painting_path(painting)
      -#%td= link_to 'Destroy', painting, :method => :delete, :data => { :confirm => 'Are you sure?' }

-#%br

-#= link_to 'New Painting', new_painting_path

app/views/paintings/new.html.haml
%h1 New painting

= render 'form'

= link_to 'Back', paintings_path

app/views/paintings/show.html.haml
.row
  .col-md-4.col-md-push-8
    %h1
      =@painting.name
      %small=@painting.gallery.name
    %p=@painting.description
    %p.buy
      =link_to "Purchase", "#", :class => "btn btn-primary"
  .col-md-8.col-md-pull-4
    =image_tag @painting.image_url(:product).to_s, :class => "img-responsive"
    

.row
  .col-md-12
    = link_to 'Edit', edit_painting_path(@painting)
    \|
    = link_to 'Back', paintings_path