config/routes.rb
Rails.application.routes.draw do
  resources :paintings

  resources :galleries

  devise_for :users
  resources :pages, :except => [:index, :new]

  get 'contacts/new', to: 'contacts#new'
  post 'contacts/create', to: 'contacts#create', as: :create_contact

  resources :homes, :except => [:index, :new]
  get ':id', to: 'homes#show' 
  root to: "homes#show", id: "home"

end

app/views/pages/_form.html.haml
= form_for @page do |f|
  - if @page.errors.any?
    #error_explanation
      %h2= "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      %ul
        - @page.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name, :class => "form-control"
  .form-group
    = f.label :content
    = f.text_area :content, :rows => 8, :class => "form-control"
  %button.btn.btn-primary{:type => "submit"}
    Save

app/views/pages/edit.html.haml
%h4 Editing page

= render 'form'

/= link_to 'Show', @page
/\|
/= link_to 'Back', pages_path

app/views/pages/index.html.haml
%h1 Listing pages

%table
  %tr
    %th Name
    %th Permalink
    %th Content
    %th
    %th
    %th

  - @pages.each do |page|
    %tr
      %td= page.name
      %td= page.permalink
      %td= page.content
      %td= link_to 'Show', page
      %td= link_to 'Edit', edit_page_path(page)
      %td= link_to 'Destroy', page, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Page', new_page_path

app/views/pages/new.html.haml
%h1 New page

= render 'form'

= link_to 'Back', pages_path

app/views/pages/show.html.haml
/%p#notice= notice
.page-header
  %h1
    =@page.name
.row
  .col-md-8
    %p
      =simple_format @page.content
.row
  .col-md-12
    = link_to 'Edit', edit_page_path(@page), :class => "btn btn-primary"
/\|
/= link_to 'Back', pages_path