config/routes.rb
Rails.application.routes.draw do
  resources :paintings

  resources :galleries

  devise_for :users
  resources :pages, :except => [:index, :new]

  get 'contacts/new', to: 'contacts#new'
  post 'contacts/create', to: 'contacts#create', as: :create_contact

  resources :homes, :except => [:index, :new]
  get ':id', to: 'homes#show' 
  root to: "homes#show", id: "home"

end

app/models/home.rb
class Home < ActiveRecord::Base
  def to_param
    permalink
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
 before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
   @paintings = Painting.all
   @paintings_group = @paintings.group_by { |p| p.gallery.name }
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find_by_permalink!(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:title, :content)
    end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.haml
= form_for @home do |f|
  - if @home.errors.any?
    #error_explanation
      %h2= "#{pluralize(@home.errors.count, "error")} prohibited this home from being saved:"
      %ul
        - @home.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :title
    = f.text_field :title, :class => "form-control"
  .form-group
    = f.label :content
    = f.text_area :content, :rows => 9, :class => "form-control"
  %button.btn.btn-primary{:type => "submit"}
    Save

app/views/homes/edit.html.haml
%h4 Editing home

= render 'form'

/= link_to 'Show', @home
/\|
/= link_to 'Back', homes_path

app/views/homes/index.html.haml
%h1 Listing homes

%table
  %tr
    %th Title
    %th Content
    %th
    %th
    %th

  - @homes.each do |home|
    %tr
      %td= home.title
      %td= home.content
      %td= link_to 'Show', home
      %td= link_to 'Edit', edit_home_path(home)
      %td= link_to 'Destroy', home, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Home', new_home_path

app/views/homes/new.html.haml
%h1 New home

= render 'form'

= link_to 'Back', homes_path

app/views/homes/show.html.haml
/ -- BANNER --
.row
  .col-lg-12.col-md-12.col-sm-12.col-xs-12
    .well.well-lg.text-center
      %h1=@home.title
      %p.lead=@home.content
      = link_to 'Edit', edit_home_path(@home), :class => "btn btn-primary"
.row
  - @paintings_group.each do |cat, paintings|
    .col-lg-6.col-md-6.col-sm-6
      %h3.text-muted=cat
      - for painting in paintings
        %p
          =link_to (image_tag painting.image_url(:product).to_s, :class => "img-responsive"), paintings_path(:type => cat.downcase), :class => "thumbnail"





/\|
/= link_to 'Back', homes_path