config/routes.rb
Rails.application.routes.draw do
  resources :paintings

  resources :galleries

  devise_for :users
  resources :pages, :except => [:index, :new]

  get 'contacts/new', to: 'contacts#new'
  post 'contacts/create', to: 'contacts#create', as: :create_contact

  resources :homes, :except => [:index, :new]
  get ':id', to: 'homes#show' 
  root to: "homes#show", id: "home"

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :paintings
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url, notice: 'Gallery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:name, :description)
    end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/galleries/_form.html.haml
= form_for @gallery do |f|
  - if @gallery.errors.any?
    #error_explanation
      %h2= "#{pluralize(@gallery.errors.count, "error")} prohibited this gallery from being saved:"
      %ul
        - @gallery.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/galleries/edit.html.haml
%h1 Editing gallery

= render 'form'

= link_to 'Show', @gallery
\|
= link_to 'Back', galleries_path

app/views/galleries/index.html.haml
%h1 Listing galleries

%table
  %tr
    %th Name
    %th Description
    %th
    %th
    %th

  - @galleries.each do |gallery|
    %tr
      %td= gallery.name
      %td= gallery.description
      %td= link_to 'Show', gallery
      %td= link_to 'Edit', edit_gallery_path(gallery)
      %td= link_to 'Destroy', gallery, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Gallery', new_gallery_path

app/views/galleries/new.html.haml
%h1 New gallery

= render 'form'

= link_to 'Back', galleries_path

app/views/galleries/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @gallery.name
%p
  %b Description:
  = @gallery.description

= link_to 'Edit', edit_gallery_path(@gallery)
\|
= link_to 'Back', galleries_path